# Generated by Django 3.1.7 on 2021-08-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20210824_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('flights', models.ManyToManyField(blank=True, related_name='passenger', to='flight.Flight')),
            ],
        ),
    ]
